name: CI - Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup .NET environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' # Adjust the version as per your project

      # Step 3: Restore NuGet packages
      - name: Restore NuGet packages
        run: dotnet restore

      # Step 4: Build the project
      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      # Step 5: Run tests
      - name: Run tests
        run: dotnet test --no-build --configuration Release
